steps:
  - template: ../steps/install-nodejs.yml
  - template: ../steps/install-dependencies.yml
  - script: yarn lint:deps
    displayName: "Check dependencies"
  - script: yarn lint:typecheck
    displayName: "Check JSDoc types"
  - script: yarn lint:eslint
    displayName: "Lint code"
  - script: yarn lint:prettier
    displayName: "Lint prettier"
  - script: yarn lint:spellcheck
    displayName: "Spellcheck"
  - script: yarn lint:changelog
    displayName: "Lint changelog"
  - script: yarn && echo "Listing changed files:" && git diff --name-only --exit-code && echo "No files changed during lint."
    displayName: "Check file changes"
